### ISSUE TITLE
 Discount (%s)

### ISSUE THREAD

**Issue by webnut-de** [themexpert/digicom#168]
In frontend the %s is shown, when no discount is added.

![bildschirmfoto 2015-08-07 um 11 05 01](https://cloud.githubusercontent.com/assets/12933331/9132526/6c71ca80-3cf4-11e5-8b90-e15529e64735.png)
![bildschirmfoto 2015-08-07 um 11 05 27](https://cloud.githubusercontent.com/assets/12933331/9132527/6c72cea8-3cf4-11e5-9fc7-b8f4850e3a7b.png)

**Comment by shamsbd71** [comment]
@webnut-de 
i was trying to find this, but didnt found. can you tell which version of digicom are you using? or where can i see it?

**Comment by webnut-de** [comment]
Im sorry for my inaccuracy. I'll try to do better :)

Its in the frontend "Order View". In backend it looks like: "Rabatt (0) -> Discount (0)".

I use the RC1 version.

**Comment by webnut-de** [comment]
Maybe it is an language fault? But i checked the language file. Seems to be ok.

**Comment by shamsbd71** [comment]
thanks, its fixed now

**Comment by webnut-de** [comment]
This issue seems to be still exists in the the order view of RC2.
